name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # æ¯å¤©åŸ·è¡Œä¸€æ¬¡
  workflow_dispatch:  # å¯æ‰‹å‹•åŸ·è¡Œ

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: weedwilly
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "generate contribution snake ğŸ"
          add: "dist/github-contribution-grid-snake.svg"
